build: fix Descent3 program link failure
In case httplibConfig.cmake is absent, there is still a link failure
because -lcpp-httplib appears nowhere on the command-line.

```
/usr/include/c++/14/bits/unique_ptr.h:1077:(.text+0x7ae9): undefined reference to `httplib::Client::Client(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/lib64/gcc/x86_64-suse-linux/14/../../../../x86_64-suse-linux/bin/ld: /usr/include/c++/14/bits/unique_ptr.h:93:(.text+0x7b0b): undefined reference to `httplib::Client::~Client()'
```

A header is not enough to get the build job done.

But… it turns out cpp-httplib can either be built as a classic
header + library combo, or installed in a header-only fashion. *sigh*
Deal with it.

Fixes: 88e487c724e6811f70c1a74dbbbb2944aad0c81e